name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun i

      - name: Build and Bundle Extension
        run: |
          bun run build
          bun run bundle

      - name: Get package version
        run: echo "package_version=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create Release with Changelog
        run: bun x changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
